version: '3.1'
services:
  db:
    image: postgres
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    command: postgres -c 'max_connections=200'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: